### ISSUE TITLE
Build 2020 Feedback Thread - Fluent UI Android

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-android#1]
Welcome Build 2020 participants! Did you get a chance to try out the Fluent UI Android library
or watch our Build 2020 talk? If so, we want to hear your feedback! Let us know how we can make this even more useful to you moving forward.

Feel free to leave feedback on any of the following (and please keep feedback constructive and respectful):

- Likes
- Dislikes
- Bugs
- Areas for improvement

Thank you,
The Fluent UI Android team

**Comment by fornewid** [comment]
I'm curious about the plan of Fluent UI.

I found the catalog page for Fluent UI.
https://developer.microsoft.com/en-us/fluentui#/controls/android

More components are provided on the web platform.
Are you planning to add more components to Android?
(like Toggle, TextField, Slider, Shimmer, Dialog, Card)

If so, it would be more nice to have a guide in a form that developers can contribute to. :)

**Comment by michaelxiao16** [comment]
Closing this for 2020
