### ISSUE TITLE
Kk

### ISSUE THREAD

**Issue by samakhomkamontip** [microsoft/fluentui-android#103]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **Android SDK version**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by FANMixco** [comment]
> ### Environment Information
> * **Package version(s)**: (fill this out, include which package manager you're using)
> * **Android SDK version**: (fill this out if relevant)
> 
> ### Please provide a reproduction of the bug:
> #### Actual behavior:
> #### Expected behavior:
> ### Priorities and help requested:
> Are you willing to submit a PR to fix? (Yes, No)
> 
> Requested priority: (Blocking, High, Normal, Low)
> 
> Products/applications affected: (if applicable)

Is this a prank question? It doesn't have anything.
