### ISSUE TITLE
Binding for Xamarin.Android

### ISSUE THREAD

**Issue by FANMixco** [microsoft/fluentui-android#105]
I'd like to see in the future a binding of these controls for Xamarin.Android or .NET for Android and publish it in NuGet.

Thanks.

**Comment by FANMixco** [comment]
It could even be considered for .NET 6 or MAUI .NET.

**Comment by joyeeta26** [comment]
Hi @FANMixco, is this still needed?

**Comment by FANMixco** [comment]
Are they available in NuGet @joyeeta26? Or this library deprecated?
