### ISSUE TITLE
PersistentBottoomSheet default content provider and make styles configurable 

### ISSUE THREAD

**Issue by mnkshukl** [microsoft/fluentui-android#11]
Current Bottomsheet requires layout to be written by consumer end. Adding a default and configurable layout source just by applying list if Items.

**Comment by joyeeta26** [comment]
Default content builder has been added - https://github.com/microsoft/fluentui-android/blob/fbf5e5bc5b613c5b3aa2ae5f5416368f0b70d2f2/fluentui_drawer/src/main/java/com/microsoft/fluentui/persistentbottomsheet/PersistentBottomSheet.kt#L373C5-L397C34

Hence closing this issue! Thanks!
cc: @Dhoot
