### ISSUE TITLE
Can you bump version of splitwise you use

### ISSUE THREAD

**Issue by snijsure** [microsoft/fluentui-android#123]
It seems FluentUI ships with an older version of com.splitwise:tokenautocomplete ( 2.0.8) it prevents app from dropping use of jetifier. 
There are convoluted ways to get around it, but it would be nice if Fluentui-android fixed the issue and see if switching to 3.X version of splitwise fixes the issue.

 Graphs to this dependency:
 +---com.microsoft.fluentui:fluentui_others:0.0.8
     +---com.splitwise:tokenautocomplete:2.0.8

For reference see 

https://github.com/dipien/bye-bye-jetifier

**Comment by snijsure** [comment]
It appears that this issue has been fixed in version 0.0.29 can someone update this ticket as to when thiis dependency was removed. We don't like to be on "bleeding edge"

**Comment by michaelxiao16** [comment]
Hi @snijsure, I will bring this issue up during our next engineering sync

**Comment by JesseScott** [comment]
Actually, it looks like this sub-module doesn't even use this library at all, but it still declares it.

If you search the repo you can see that the People Picker module is the only one that uses it.
This should have been removed in #93 but was missed.

So you can simply remove the dependency from this module

**Comment by JesseScott** [comment]
PR up in #305

**Comment by joyeeta26** [comment]
tokeautomcomplete dependency was removed as part of PR #305. Hence closing this issue
