### ISSUE TITLE
app-debug.apk for showcasing UI 

### ISSUE THREAD

**Issue by virtualvivek** [microsoft/fluentui-android#133]
Hi Microsoft Team,

Thanks for bringing fluent UI for android platform,
Can you please add the `app-debug.apk` file 
as when I check didn't find it yet, if its there please let me know by providing us some link to it.

Hope it would be love by the android devs.!!!

**Comment by joyeeta26** [comment]
the debug apk will be located in FluentUI.Demo/build/outputs/apk/
Closing this issue, Please feel free to reopen if there are any further questions

**Comment by virtualvivek** [comment]
Hi @joyeeta26 

Thanks for your response

However been 2 weeks this issue resolved i was wondering if directory *FluentUI.Demo/build/outputs/apk/* really there ?

**Comment by joyeeta26** [comment]
Hi @virtualvivek, you need to build the demo app for this to be present
