### ISSUE TITLE
Drawer is misaligned 

### ISSUE THREAD

**Issue by pavelprystinka** [microsoft/fluentui-android#156]
### Environment Information

- **Package version(s)**: Maven, 0.0.14
- **Android SDK version**: API level 30, Device: Samsung Galaxy S10

### Please provide a reproduction of the bug:
On the other devices works as expected:

#### Actual behavior:

Items in the drawer got shifted to the right: 
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/30868871/154109661-274c4bf0-a21d-4607-8718-bd2e8e2b4dff.png">

#### Expected behavior:
Works as expected on other device:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/30868871/154111626-1e41cee1-0942-4dea-8554-7bbf2be1c8c1.png">

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by joyeeta26** [comment]
Hi @pavelprystinka, are you still facing this issue?

**Comment by joyeeta26** [comment]
Closing this issue. Please feel free to reopen if the issue still persists.
