### ISSUE TITLE
Unable to remove the ring from STACK style inAvatarGroupView

### ISSUE THREAD

**Issue by sushmithaaluru** [microsoft/fluentui-android#166]
#### Describe the feature that you would like added

I am using fluent ui - AvatarGroupView to display the stack of profile pictures in our app , and found that we cannot remove the ring around the Avatarimage from being displayed 
this is because the when we apply avatarstyle as STACK the default implementation is having RING added 

However on fluentui-iOS we are able to remove the border around the images from AvatarGroupView class

Hence we want your help in updating the style on fluentui android AvatarGroupView so that we can seamlessly integrate with our app
#### What component or utility would this be added to

AvatarGroupView
#### Have you discussed this feature with our team, and if so, who

No

**Comment by joyeeta26** [comment]
Hey @sushmithaaluru, this feature is available now, border styles can be passed to AvatarGroupView.
without border
![image](https://github.com/user-attachments/assets/5b7d488f-88c6-4ef6-b23b-5ca8139c8730)

with border
![image](https://github.com/user-attachments/assets/04f18f1c-a1f4-46c7-bd7b-d316bd1c3b84)

Closing this issue
cc: @Dhoot @michaelxiao16
