### ISSUE TITLE
with AvatarGroupView set bitmap Image not reflecting on UI.

### ISSUE THREAD

**Issue by ishantagarwal20** [microsoft/fluentui-android#169]
Hi Team,

We are using fluent-ui in our Android Defender app and found the issue with bitmap image that is set in IAvatar. Once the image is set in IAvatar and list of IAvatars is set in AvatarGroupView, the image doesn't reflect on UI infact a fallback image that is created using the user's initials shows up on the UI. For now we have moved to the api setAvatarImageDrawable rather than setAvatarImageBitmap, and it has unblocked us for now. 

Thanks

**Comment by praveen970** [comment]
issue fixed in release 0.0.32
