### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by tystratt** [microsoft/fluentui-android#17]
according to the readme:

> We use GitHub Releases to manage our releases, including the changelog between every release. You'll find a complete list of additions, fixes, and changes on the Releases page.

but all of the releases at https://github.com/microsoft/fluentui-android/releases

just say "New Release" or  "Version releases x.x.x". no detail on what has been changed.

**Comment by aishwarya56** [comment]
This is still in very initial stages, You will start seeing proper release details fom next versions that is from release 0.0.8
