### ISSUE TITLE
(Figma component) When replacing a list icon button with a toggle control, the toggle knob is incorrectly positioned

### ISSUE THREAD

**Issue by samhenrigold** [microsoft/fluentui-android#179]
<img width="1252" alt="Screen Shot 2022-04-05 at 9 45 07 AM" src="https://user-images.githubusercontent.com/49251320/161768522-76b94d03-d666-4eaa-ab2b-9bb11e096308.png">

<img width="1911" alt="Screen Shot 2022-04-05 at 9 45 26 AM" src="https://user-images.githubusercontent.com/49251320/161768535-56f9ebc3-ad98-4c2c-b7db-74f0119fbb8e.png">

### Please provide a reproduction of the bug:

Add a list component (I'm using `01. Single-Line / 01. Standard / ⚪️ C. With Icon - Light`), select the trailing icon which should be a 24x24 square frame, replace it with a non-square component like a toggle control.

#### Actual behavior:

Knob is centered

#### Expected behavior:

Knob is on one of the edges of the track, not centered.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/applications affected: Figma design library

**Comment by joyeeta26** [comment]
which fluent version are you using?
this issue doesn't seem to repro now. Please feel free to reopen if it's still happening. 
Closing this issue for now!
Thanks!
