### ISSUE TITLE
Incorrect signature for DrawerDialog::dispatchKeyEvent 

### ISSUE THREAD

**Issue by snijsure** [microsoft/fluentui-android#187]
We have DrawerDialog implementation, that extends Fluent's DrawerDialog.

I am upgrading fluent version 0.0.11 to 0.0.20

I am encountering the following error,  ( Note I have stripped our internal package names)

```
e: .../NotificationSubscriptionDrawerDialog.kt: (18, 7): Inherited platform declarations clash: The following declarations have the same JVM signature (dispatchKeyEvent(Landroid/view/KeyEvent;)Z):
    fun dispatchKeyEvent(p0: KeyEvent): Boolean defined in ........NotificationSubscriptionDrawerDialog
    fun dispatchKeyEvent(event: KeyEvent?): Boolean defined in ...NotificationSubscriptionDrawerDialog
e: ...../OverflowActionDrawerDialog.kt: (27, 7): Inherited platform declarations clash: The following declarations have the same JVM signature (dispatchKeyEvent(Landroid/view/KeyEvent;)Z):
    fun dispatchKeyEvent(p0: KeyEvent): Boolean defined in ......OverflowActionDrawerDialog
    fun dispatchKeyEvent(event: KeyEvent?): Boolean defined in .....OverflowActionDrawerDialog
```

I think this is because of DrawerDialog::dispatchKeyEvent  signature?

It is declared as
```
    override fun dispatchKeyEvent(event: KeyEvent?): Boolean {
```

Instead should be declared as

```
    override fun dispatchKeyEvent(event: KeyEvent): Boolean {
```

**Comment by joyeeta26** [comment]
This has been fixed! Please refer latest code 
https://github.com/microsoft/fluentui-android/blob/fbf5e5bc5b613c5b3aa2ae5f5416368f0b70d2f2/fluentui_drawer/src/main/java/com/microsoft/fluentui/drawer/DrawerDialog.kt#L161C1-L168C1
Closing this issue! Thanks!
cc: @Dhoot
