### ISSUE TITLE
Use version of TokenAutoComplete library that supports AndroidX

### ISSUE THREAD

**Issue by phileo99** [microsoft/fluentui-android#192]
### Environment Information

- **Package version(s)**:  com.microsoft.fluentui:fluentui_others:0.0.20

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority:  High

**Comment by JesseScott** [comment]
Duplicate of #123

**Comment by joyeeta26** [comment]
tokenautomcompleteversion was removed as part of PR #305. Hence closing this issue
