### ISSUE TITLE
Coherence across different platform for fluent UI controls

### ISSUE THREAD

**Issue by atishayv** [microsoft/fluentui-android#30]
**Describe the feature that you would like added**
The fluent ui controls across different platform are not exactly the same. For ex : If you look at Basic Inputs supported in Android by fluent ui
![image](https://user-images.githubusercontent.com/13940020/101194876-9d71dc80-3684-11eb-930e-e4ff1a707e5c.png)

which is a lot less when compared with Web :
![image](https://user-images.githubusercontent.com/13940020/101195120-f80b3880-3684-11eb-9ab4-0c1cee18b48c.png)

Is there a plan to make all controls same across different platforms ? Also can you give me an idea on whats the rough timeline for the same ?

**Comment by Saadnajmi** [comment]
@aneeshack4 @ejlayne

**Comment by atishayv** [comment]
@Saadnajmi , @aneeshack4 , @ejlayne Gentle ping on this

**Comment by aishwarya56** [comment]
Hey @atishayv, Yes the plan is to make all controls available for android too.
Also, we are actively working on adding new components. Many new components are available in the demo apk, which have not been yet reflected on the website

**Comment by mehulchandroliya** [comment]
I wanted to build my new project using Fluent UI for android but there is a missing basic control where we can capture user input mostly like a single or multi-line Text Box. If it is already supported happy to contribute with an updated demo app.

**Comment by joyeeta26** [comment]
textField is now available
a lot of other controls are also available now. Please refer fluent v2
Please let us know if there is any other specific control you are looking for. 
Closing this issue for now! Thanks!
