### ISSUE TITLE
V2 Drawer (Bottom) - Scroll, then expand instead of the other way around

### ISSUE THREAD

**Issue by yemi33** [microsoft/fluentui-android#301]
#### Describe the feature that you would like added

Right now the default behavior for Bottom Drawer when the drawer content's full height is taller than the height of the drawer is:
1. User does an 'up' gesture anywhere in the drawer (handle, drawer content)
2. Drawer expands to the entire screen (if content taller than or equal to the screen height)
3. If the content is taller than the screen height and content is a lazy list that is scrollable, user can scroll to see the entire list 

I would like it to be (and this is the behavior of Google Bottom Drawer/Sheet):
1. User does an 'up' gesture **within**  the drawer content 
2. Drawer maintains same height and allows user to scroll 
3. If the drawer **handle** experiences the 'up' gesture, drawer expands 

#### What component or utility would this be added to

This will greatly help in Loop Android's effort to implement Bottom Sheet inside the Workspace page editor. 

#### Have you discussed this feature with our team, and if so, who

Mayank Mishra

#### Additional context/screenshots

**Comment by mishramayank1** [comment]
Solution has been provided in PR  https://github.com/microsoft/fluentui-android/pull/339
