### ISSUE TITLE
TextStyle function that gets used in Tokenized Button doesn't exists anymore

### ISSUE THREAD

**Issue by yemi33** [microsoft/fluentui-android#338]
While using Fluent V2Button I got the following error:

`java.lang.NoSuchMethodError: 'void androidx.compose.ui.text.TextStyle. (long, long, androidx.compose.ui.text.font.FontWeight, androidx.compose.ui.text.font.FontStyle, androidx.compose.ui.text.font.FontSynthesis, androidx.compose.ui.text.font.FontFamily, java.lang.String, long, androidx.compose.ui.text.style.BaselineShift, androidx.compose.ui.text.style.TextGeometricTransform, androidx.compose.ui.text.intl.LocaleList, long, androidx.compose.ui.text.style.TextDecoration, androidx.compose.ui.graphics.Shadow, androidx.compose.ui.text.style.TextAlign, androidx.compose.ui.text.style.TextDirection, long, androidx.compose.ui.text.style.TextIndent, androidx.compose.ui.text.PlatformTextStyle, int, _layoutlib_._internal_.kotlin.jvm.internal.DefaultConstructorMarker)'   at com.microsoft.fluentui.tokenized.controls.ButtonKt$Button$2.invoke(Button.kt:134)   at com.microsoft.fluentui.tokenized.controls.ButtonKt$Button$2.invoke(Button.kt:57)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at com.microsoft.fluentui.tokenized.controls.ButtonKt.Button(Button.kt:54)`

I looked at that file, but line 134 of Button.kt is calling TextStyle method which is experimental and likely is no longer supported.

**Comment by Anubhvv** [comment]
> While using Fluent V2Button I got the following error:
> 
> `java.lang.NoSuchMethodError: 'void androidx.compose.ui.text.TextStyle. (long, long, androidx.compose.ui.text.font.FontWeight, androidx.compose.ui.text.font.FontStyle, androidx.compose.ui.text.font.FontSynthesis, androidx.compose.ui.text.font.FontFamily, java.lang.String, long, androidx.compose.ui.text.style.BaselineShift, androidx.compose.ui.text.style.TextGeometricTransform, androidx.compose.ui.text.intl.LocaleList, long, androidx.compose.ui.text.style.TextDecoration, androidx.compose.ui.graphics.Shadow, androidx.compose.ui.text.style.TextAlign, androidx.compose.ui.text.style.TextDirection, long, androidx.compose.ui.text.style.TextIndent, androidx.compose.ui.text.PlatformTextStyle, int, _layoutlib_._internal_.kotlin.jvm.internal.DefaultConstructorMarker)'   at com.microsoft.fluentui.tokenized.controls.ButtonKt$Button$2.invoke(Button.kt:134)   at com.microsoft.fluentui.tokenized.controls.ButtonKt$Button$2.invoke(Button.kt:57)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at com.microsoft.fluentui.tokenized.controls.ButtonKt.Button(Button.kt:54)`
> 
> I looked at that file, but line 134 of Button.kt is calling TextStyle method which is experimental and likely is no longer supported.

Hey, at that time jetpack compose didn't fully support TextStyle and it was in experimental phase. Since, jetpack compose 1.0.0, TextStyle is being fully supported by jetpack compose, we are also removing the experimental APi, and will using the fully supported one. 
Fluent v 0.1.39 will have this fix.
