### ISSUE TITLE
Prefix all attrs with a unique label

### ISSUE THREAD

**Issue by daniel-robertson** [microsoft/fluentui-android#42]
#### Describe the feature that you would like added

In order to prevent naming conflicts with other libraries and apps, it is best to prefix attrs with something unique. I think `fluentui` makes the most sense given that the attrs in `attrs.xml` are already prefixed with it.

#### What component or utility would this be added to

Files such as `attrs_avatar.xml`, `attrs_people_picker.xml`, `attrs_avatar_group.xml`, etc. all need to have unique attrs to avoid conflicts.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
Compiling the library into our app results in compilation errors such as:
`AAPT: error: duplicate value for resource 'attr/type' with config ''. `
`AAPT: error: duplicate value for resource 'attr/avatarSize' with config ''.`

**Comment by ejlayne** [comment]
@aishwarya56 Daniel reached out to me about this, we should make sure this is addressed for vNext components. Let me know if you have any questions.

**Comment by KyleCorio** [comment]
Has this been fixed with the latest release? https://teams.microsoft.com/l/message/19:300100986bed417b83cc841f9404fffa@thread.skype/1645126104937?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ffe264f2-14d0-48b5-9384-64f808b81294&parentMessageId=1645126104937&teamName=Fluent%20Community&channelName=Fluent%20UI%20Android&createdTime=1645126104937

@michaelxiao16 @ejlayne  @aishwarya56

**Comment by joyeeta26** [comment]
Hi @KyleCorio, this has been fixed, refer the following-
https://github.com/microsoft/fluentui-android/blob/master/fluentui_persona/src/main/res/values/attrs_avatar.xml
https://github.com/microsoft/fluentui-android/blob/master/fluentui_peoplepicker/src/main/res/values/attrs_people_picker.xml
https://github.com/microsoft/fluentui-android/blob/master/fluentui_persona/src/main/res/values/attrs_avatar_group.xml

Closing this issue! Thanks!
cc: @michaelxiao16 @Dhoot
