### ISSUE TITLE
Snackbar shows with no backround when launched from Fragment

### ISSUE THREAD

**Issue by bergestahl** [microsoft/fluentui-android#45]
The text and the custom view is visible, the dark grey background is not

Tried these ways, all the same result:

Snackbar.make(requireActivity().findViewById(android.R.id.content), message,Snackbar.LENGTH_LONG)
            .setCustomView(avatarView, Snackbar.CustomViewSize.MEDIUM)
            .setStyle(Snackbar.Style.REGULAR)
            .show()

Snackbar.make(requireView(), message, Snackbar.LENGTH_LONG)
            .setCustomView(avatarView, Snackbar.CustomViewSize.MEDIUM)
            .setStyle(Snackbar.Style.REGULAR)
            .show()

Snackbar.make(requireActivity().findViewById(R.id.activity_root), message,Snackbar.LENGTH_LONG)
            .setCustomView(avatarView, Snackbar.CustomViewSize.MEDIUM)
            .setStyle(Snackbar.Style.REGULAR)
            .show()

**Comment by joyeeta26** [comment]
Hey @bergestahl, can you please add screenshot or video of the issue here?
Also try using v2 snackbar.
Thanks!

**Comment by joyeeta26** [comment]
Closing this issue for now! Please feel free to reopen with screenshot/video of the issue if it's still happening.
Thanks!
