### ISSUE TITLE
Failed to resolve: com.microsoft.device:dualscreen-layout:1.0.0-alpha01

### ISSUE THREAD

**Issue by azuredivay** [microsoft/fluentui-android#5]
Build issue when updating gradle version of Fluent UI implementation to 0.0.4 
`    implementation 'com.microsoft.fluentui:FluentUIAndroid:0.0.4'`

Grade issue disappears at 0.0.3. 
minSdkVersion 22
targetSdkVersion 29
compileSdkVersion 29
buildToolsVersion "29.0.2"

**Comment by tamasane** [comment]
Sync Project with Gradle files, solves the issue.

**Comment by azuredivay** [comment]
I did, also cleaned and tried to rebuild, neither helped in 0.0.4, 0.0.3 still works fine

**Comment by aaronspooky** [comment]
I don't know why, but if you add this to the top-level build.gradle file, it works:

`allprojects {
   repositories {
       maven {
           url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1"
       }
   }
}`

Microsoft documentation: https://docs.microsoft.com/en-us/dual-screen/android/api-reference/dualscreen-layout?tabs=java

**Comment by tamasane** [comment]
@aaronspooky It is already present in the top-level build.gradle file, https://github.com/microsoft/fluentui-android/blob/master/build.gradle
@azuredivay I am unable to produce this issue. The gradle build completes successfully without any issue. Please try recloning the project.

**Comment by azuredivay** [comment]
@tamasane The issue wasn't from cloing this project, it was from adding Fluent UI as a dependency in a new android project, apparently version 0.0.4 depends on what @aaronspooky pointed out, so it fails to build as the package itself doesn't contain it

**Comment by postfixNotation** [comment]
> Build issue when updating gradle version of Fluent UI implementation to 0.0.4
> ` implementation 'com.microsoft.fluentui:FluentUIAndroid:0.0.4'`
> 
> Grade issue disappears at 0.0.3.
> minSdkVersion 22
> targetSdkVersion 29
> compileSdkVersion 29
> buildToolsVersion "29.0.2"

I'm experiencing the exact same issue! minSdkVersion is 21 though, but that's not the point.

**Comment by azuredivay** [comment]
@postfixNotation's solution worked!

**Comment by truedat101** [comment]
Why is this closed if it is a work around and isn't integrated into the instructions?

**Comment by truedat101** [comment]
So the instructions include the obscure "surface-duo" https://github.com/microsoft/fluentui-android#a-develop-for-surface-duo

in the main readme, however, it is presented as if this is an option, in case you are developing for surface-duo.  It should just be required configuration.
