### ISSUE TITLE
[TalkBack] Talkback not announcing selected pill button index in PillBar V2

### ISSUE THREAD

**Issue by yemi33** [microsoft/fluentui-android#536]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **Android SDK version**: 0.1.38

### Please provide a reproduction of the bug:

1. Use Fluent V2 PillBar component (Compose) with at least two pill metadata (two pill buttons)
2. Turn on 'TalkBack' screen reader

#### Actual behavior:
When selecting a pill button within the PillBar, TalkBack is announcing only the name of the button and its selected / enabled state

#### Expected behavior:

When selecting a pill button within the PillBar, TalkBack must also announce the index of the button within the PillBar to indicate that there are multiple pills within the PillBar. Ex. "All" tab item 1 of 2, in list 2 items..etc

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) **High (Accessibility)**

Products/applications affected: (if applicable)

**Comment by Anubhvv** [comment]
#547 
This merged PR addresses and resolves this issue.

**Comment by Anubhvv** [comment]
> ### Environment Information
> * **Package version(s)**: (fill this out, include which package manager you're using)
> * **Android SDK version**: 0.1.38
> 
> ### Please provide a reproduction of the bug:
> 1. Use Fluent V2 PillBar component (Compose) with at least two pill metadata (two pill buttons)
> 2. Turn on 'TalkBack' screen reader
> 
> #### Actual behavior:
> When selecting a pill button within the PillBar, TalkBack is announcing only the name of the button and its selected / enabled state
> 
> #### Expected behavior:
> When selecting a pill button within the PillBar, TalkBack must also announce the index of the button within the PillBar to indicate that there are multiple pills within the PillBar. Ex. "All" tab item 1 of 2, in list 2 items..etc
> 
> ### Priorities and help requested:
> Are you willing to submit a PR to fix? (Yes, No)
> 
> Requested priority: (Blocking, High, Normal, Low) **High (Accessibility)**
> 
> Products/applications affected: (if applicable)

Hey Yemi, this talkback ask has been released in fluent 0.1.40.
Hence, closing this issue.
