### ISSUE TITLE
Dualscreen-layout dependency causes the project to fail to build properly

### ISSUE THREAD

**Issue by whitescent** [microsoft/fluentui-android#566]
when I tried to add the FluentUI dependency to my project, I found that the dualscreen-layout dependency didn't download properly

![image](https://github.com/microsoft/fluentui-android/assets/31311826/0baf0317-a28e-454c-8876-5c4d4b886300)

And the project doesn't pass the compilation properly

![image](https://github.com/microsoft/fluentui-android/assets/31311826/ecd5e20b-a869-496f-9690-77aaac6e194f)

then, i found this issue: https://github.com/microsoft/fluentui-android/issues/5

when i add this maven source, it can be solved, and the project can also work with bulid and run

> allprojects { repositories { maven { url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1" } } }

I don't want to develop for Surface-Duo devices, I just want to use FluentUI into my app
And My dependencies are just `implementation 'com.microsoft.fluentui:FluentUIAndroid:$version'`
But it seems to depend on the dualscreen-layout

So do I need to submit a PR to the README to tell others about this issue?

**Comment by vanjib1** [comment]
Has there been any progress on this issue? I'm running into the same problem, and it's made worse when dealing with lockfiles and unified maven feed 
![image](https://github.com/user-attachments/assets/093ef4ad-dfbb-4f93-b56c-b5213c3bf661)

**Comment by joyeeta26** [comment]
Hey @vanjib1, you can try adding this maven source to resolve the issue
maven {
    url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1"
}

Hey @whitescent, fluent components are customised for surface duo, hence this dependency is included in the module
I will update the README to madatorily include the above maven url

**Comment by joyeeta26** [comment]
Hi @vanjib1 @whitescent dualscreen layout dependency has been removed with version 0.3.4
