### ISSUE TITLE
In dependencies example for README, publish the current released version to use instead of using a $version tag

### ISSUE THREAD

**Issue by truedat101** [microsoft/fluentui-android#57]
### Environment Information
Android studio 4

### Please provide a reproduction of the bug:
https://github.com/microsoft/fluentui-android#1-using-gradle

says to use implementation 'com.microsoft.fluentui:FluentUIAndroid:$version'

Well obviously that won't work.  Below it says to use the correct version.  Just put in the correct version instead of having the user hunt the tags or search mvnrepository.

#### Actual behavior:

error

#### Expected behavior:

no error

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) yes

Requested priority: (Blocking, High, Normal, Low)low

Products/applications affected: (if applicable)anyone trying out your getting started section

**Comment by joyeeta26** [comment]
The README has been created in a generic way instead of specifying a fixed version, so that the user can plug in the required version as per need. Closing this issue! Feel free to reopen if there are further questions! Thanks!
