### ISSUE TITLE
java.lang.IllegalArgumentException: The target value must have an associated anchor

### ISSUE THREAD

**Issue by whitescent** [microsoft/fluentui-android#598]
### Environment Information

- **Package version(s)**: 0.1.46

### Please provide a reproduction of the bug:

The BottomDrawer crashes when the IME keyboard is open 

https://github.com/microsoft/fluentui-android/assets/31311826/cd142ac6-f29d-4798-a207-d35d4128912d

### Priorities and help requested:

Are you willing to submit a PR to fix? NO

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/applications affected: (if applicable)

**Comment by whitescent** [comment]
this problem is very strange, sometimes when the IME keyboard is open, it can still open the BottomDrawer normally, but when it crashes, it is always with the keyboard open

**Comment by mishramayank1** [comment]
@whitescent 
This issue has been addressed in 0.1.47. Please try & reopen the ticket if the issue persist.
