### ISSUE TITLE
Naming issue - OnDismissListener in Drawer.kt

### ISSUE THREAD

**Issue by postfixNotation** [microsoft/fluentui-android#6]
https://github.com/microsoft/fluentui-android/blob/2f9491e8d98721a4672bf1e462b78fcbec979ce0/FluentUI/src/main/java/com/microsoft/fluentui/drawer/Drawer.kt#L41

`fun onDrawerDismissListener()` should be renamed to something like `fun onDrawerDismissed()`

**Comment by joyeeta26** [comment]
closing this issue, we now have Drawer v2 available
