### ISSUE TITLE
Unable to dismiss bottom drawer when predictive back gesture is on

### ISSUE THREAD

**Issue by lazzzis** [microsoft/fluentui-android#602]
### Environment Information

- **Package version(s)**: 0.1.46
- **Android SDK version**: Android T or above is required

### Please provide a reproduction of the bug:

I am working on refactoring my app to support Android's [predictive back gesture](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture), which is expected to be enabled by default from Android 15.

To test it on Android 13 and 14, following these instructions:

1. Enable Develop options -> Predictive back animations
2. add `android:enableOnBackInvokedCallback="true"` in [AndroidManifest.xml](https://github.com/microsoft/fluentui-android/blob/4b780d48b7868cd1b37998d6d9d4b2d8cb7427fa/FluentUI.Demo/src/main/AndroidManifest.xml#L12)
3. Launch FluentUi.Demo -> V2 Components -> V2 Bottom Drawer -> Open Drawer
4. swipe back or press back button

#### Actual behavior:

Unable to dismiss the bottom drawer.

#### Expected behavior:

Swiping back should dismiss the bottom drawer.

### Priorities and help requested:

Are you willing to submit a PR to fix?

Okay but need guidance. I know the reason why it fails is because currently ModalPopup relies on KEYCODE_BACK to handle back events.

https://github.com/microsoft/fluentui-android/blob/4b780d48b7868cd1b37998d6d9d4b2d8cb7427fa/fluentui_core/src/main/java/com/microsoft/fluentui/compose/ModalPopup.kt#L213

But per android's doc, once predictive back gesture is enabled, Android OS will not send KEYCODE_BACK when back button is pressed. The solution is to migrated to [OnBackPressedDispatcher](https://developer.android.com/reference/androidx/activity/OnBackPressedDispatcher) as suggested by Android's official guide. But due to potential complexities, I am not very confident to refactor ModalPopup without guidance.

<img width="834" alt="Screenshot 2024-01-28 at 11 44 06 PM" src="https://github.com/microsoft/fluentui-android/assets/10359255/f79a0dbf-7265-4947-b84b-aa4d48d09dfa">

Requested priority: High

**Comment by Dhruv-Mishra** [comment]
Hey @lazzzis I don't see the option to enable predictive back animations within the developer options on both my android 14 and android 15 emulated pixel devices, can you share which device you are using?

**Comment by lazzzis** [comment]
Android 14, Pixel 5a. ![Image](https://github.com/user-attachments/assets/d6ee059f-fda3-42b8-8813-04d0c010ce73)

**Comment by Dhruv-Mishra** [comment]
Hey @lazzzis would you be comfortable scheduling a meeting about this issue?

**Comment by Dhruv-Mishra** [comment]
Hey @lazzzis , I have raised a PR to fix the same for bottomDrawers;

https://github.com/microsoft/fluentui-android/pull/744

Will close the issue after the next release
