### ISSUE TITLE
Scrolling down on a Bottom Drawer dismisses it too easily

### ISSUE THREAD

**Issue by yemi33** [microsoft/fluentui-android#638]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using) 0.2.1
- **Android SDK version**: (fill this out if relevant)

### Please provide a reproduction of the bug:

* Use Drawer component with BehaviorType.BOTTOM
* Scroll on the content of the drawer with a downward motion close to the gripper but not on the gripper

#### Actual behavior:

The drawer gets dismissed.

#### Expected behavior:

The drawer gets too easily dismissed, when the desired behavior is to not dismiss the drawer unless the gripper was explicitly grabbed.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by Anubhvv** [comment]
Hey @yemi33, right now downward drag threshold is 56.dp for bottomDrawer.
can you check sticky downward threshold drag available in Bottom Sheet, user can customize it.

**Comment by joyeeta26** [comment]
Hi @yemi33, is this still an issue?

**Comment by joyeeta26** [comment]
Closing this. Feel free to reopen if this is still an issue. Thanks!
