### ISSUE TITLE
Scaffold adds top bar padding when top bar is not present

### ISSUE THREAD

**Issue by CarlosUrbina** [microsoft/fluentui-android#656]
### Environment Information

- **Package version(s)**: 0.2.7

### Please provide a reproduction of the bug:

Using the Scaffold V2 with topBar and content parameters

#### Actual behavior:

Content slot still has a topPadding matching the topBar, even when this is not present

![image](https://github.com/microsoft/fluentui-android/assets/388868/90a6902b-d438-46e5-88c8-671831cd8633)

#### Expected behavior:

Content slot only has top padding when the topBar is present

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by joyeeta26** [comment]
Not reproable.
As discussed with @CarlosUrbina, closing the issue for now!
Thanks!

cc: @Dhoot
