### ISSUE TITLE
Make the TabBar's text size adjustable

### ISSUE THREAD

**Issue by CarlosUrbina** [microsoft/fluentui-android#662]
#### Describe the feature that you would like added

Currently, the text size of the `TabItem` is fixed, determined by the defaults in the `TextStyle`. Would like to have an entry in `TabItemTokens` to provide a custom size

#### What component or utility would this be added to

`TabItemTokens` and `TabItem`

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
![image](https://github.com/microsoft/fluentui-android/assets/388868/dc075ab7-dae3-4d76-a813-014de36b8fb2)
![image](https://github.com/microsoft/fluentui-android/assets/388868/3ef1fcd0-2300-407c-9604-52813355ef1d)

**Comment by joyeeta26** [comment]
Fixed with #697

**Comment by joyeeta26** [comment]
it's available now with release 0.3.1, hence closing this issue
cc: @Dhoot @michaelxiao16
