### ISSUE TITLE
Drawer does not respect navigation bars on tablets

### ISSUE THREAD

**Issue by CarlosUrbina** [microsoft/fluentui-android#666]
### Environment Information

- **Package version(s)**: 0.2.7

### Please provide a reproduction of the bug:

In edge to edge mode, when the drawer is displayed, the content appears behind the navigation bar

#### Actual behavior:
Only occurs on tablets
![image](https://github.com/microsoft/fluentui-android/assets/388868/95af4613-2a66-4051-9960-9c43ddce33f8)

#### Expected behavior:
Behaves similar to the drawer running on a phone
![image](https://github.com/microsoft/fluentui-android/assets/388868/e9569cf4-4a5d-41fc-8a55-10f6bce76b7b)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/applications affected: Microsoft Loop

**Comment by Anubhvv** [comment]
Hey @CarlosUrbina, what android version is the tablet on? and how did you enable edge to edge on it?

**Comment by Dhruv-Mishra** [comment]
Hey @CarlosUrbina, is this the expected behavior for you?
![image](https://github.com/user-attachments/assets/2afa9311-fa81-4bf3-b229-b48dc2437884)

**Comment by Dhruv-Mishra** [comment]
Hey @CarlosUrbina are you using V2 drawers or V1? Also, if you are using V2 does enabling slideOver within the V2 Drawer work for your use case?

**Comment by CarlosUrbina** [comment]
Confirmed this is fixed in the latest version
![Image](https://github.com/user-attachments/assets/31b31285-6770-4fc9-a98b-6e87748d9a4d)
