### ISSUE TITLE
FluentUI Calendar datepicker dialog doesn't adjust itself according to orientation of device

### ISSUE THREAD

**Issue by ManasGupta1310** [microsoft/fluentui-android#678]
### Environment Information

- **Package version(s)**: Latest Version of FluentUI-Android
- **Android SDK version**: 

### Please provide a reproduction of the bug:
Device: Pixel 5 Android API 29

[OrientationIssue.webm](https://github.com/user-attachments/assets/79341c95-18bd-4868-8e0d-fd28b0717351)

#### Actual behavior:

On orientation shift from horizontal to vertical, the datepicker dialog goes out of the viewport.

#### Expected behavior:

On orientation change, the dialog should adjust the size itself.

### Priorities and help requested:

Are you willing to submit a PR to fix? 

Requested priority: Normal

Products/applications affected: Excel Mobile Application

**Comment by Anubhvv** [comment]
Hey @ManasGupta1310, I tried to test the same in fluent-ui Demo App on Pixel 5 sdk 29, but it seems to be working fine.
[Uploading date-picker orientation.webm…]()

**Comment by ManasGupta1310** [comment]
Well, it does not repro for the DateTimePicker but I had implemented the **DateTimePickerDialog** in the app. Can you try to repro the issue in that @Anubhvv 

The last button in this screenshot
![c166440a-63d6-4635-bf4b-98bfdc52dbcf](https://github.com/user-attachments/assets/4d465ee6-58b1-4daf-a07f-855b0b0a7188)

**Comment by Anubhvv** [comment]
This issue has been addressed in https://github.com/microsoft/fluentui-android/pull/679
