### ISSUE TITLE
Jetpack Compose Intergration

### ISSUE THREAD

**Issue by smallshen** [microsoft/fluentui-android#87]
#### Describe the feature that you would like added

Using Jetpack Compose to draw Fluent UI

#### What component or utility would this be added to

Prob everything

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Google announced that Jetpack Compose will be the future of the Android UI toolkit, I think there should be a Jetpack Compose version of Fluent UI

Also, Jetpack Compose is cross-platform and supports desktop. Single integration will work on multiple platforms, it is cool.

**Comment by tscholze** [comment]
Hi there,
any update on this issue? :)

**Comment by NamanPandey** [comment]
We are working on to creating components using jetpack compose and have actually released first version with Button and FAB. Release Link: https://github.com/microsoft/fluentui-android/releases/tag/0.1.0

FluentUI will be coming up with more controls over the next few months.

**Comment by tscholze** [comment]
Thank!

**Comment by smallshen** [comment]
@NamanPandey I think it would be better to separate compose implementation from originals. Jetpack compose is multiplatform, which means we can bring fluentui to other platforms, not only android.
