### ISSUE TITLE
BUG: Initials of Thursday and Sunday in Polish are wrong

### ISSUE THREAD

**Issue by sudka** [microsoft/fluentui-android#9]
The first letters displayed in the calendar for the days of the week are wrong for Thursday and Sunday in the Polish language.
For Thursday it is supposed to be **C**(Czwartek) instead of W and for Sunday it is supposed to be **N**(Niedziela) instead of S.

Fix: https://github.com/microsoft/fluentui-android/pull/8

**Comment by joyeeta26** [comment]
This bug has been fixed, Refer below references

https://github.com/microsoft/fluentui-android/blob/15b547f7ca9cd519a2aeb308f086b29dc1b3c8cc/fluentui_calendar/src/main/res/values-pl-rPL/strings.xml#L19C1-L21C78

https://github.com/microsoft/fluentui-android/blob/15b547f7ca9cd519a2aeb308f086b29dc1b3c8cc/fluentui_calendar/src/main/res/values-pl-rPL/strings.xml#L28C1-L30C74

Closing this issue. Thanks!
cc: @Dhoot @michaelxiao16
